# README

This Sample application just checks if the `Copyright` information is being printed
on the console for proper configuration for building sample SystemC application.

Please add the configuration (`SystemC.config`) generated by the
`build.sh` script after the SystemC library has been built by it.

**Note:** Please restart your shell session or just source the `~/.bashrc` file to update
Environment variables.
