INCLUDE (InstallRequiredSystemLibraries)

SET (CPACK_PACKAGE_VENDOR "Foo Training")
SET (CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

SET (CPACK_PACKAGE_INSTALL_DIRECTORY "CMake ${CMake_VERSION_MAJOR}.${CMake_VERSION_MINOR}")

SET (CPACK_DEBIAN_PACKAGE_MAINTAINER "Ameya Vikram Singh") #required

#include (${PROJECT_BINARY_DIR}/CPackConfig.cmake)
